// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBopzbuU2V23bqJSXWld50QO54aEuaHHUo',
    appId: '1:864142541207:web:a616592b2fbaf1963d44d2',
    messagingSenderId: '864142541207',
    projectId: 'complexusdemo-3bc02',
    authDomain: 'complexusdemo-3bc02.firebaseapp.com',
    databaseURL: 'https://complexusdemo-3bc02.firebaseio.com',
    storageBucket: 'complexusdemo-3bc02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4OHpPimrScjIqHr9g4YSAvEiJztYvjgQ',
    appId: '1:864142541207:android:4dcf7e8c472017323d44d2',
    messagingSenderId: '864142541207',
    projectId: 'complexusdemo-3bc02',
    databaseURL: 'https://complexusdemo-3bc02.firebaseio.com',
    storageBucket: 'complexusdemo-3bc02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwgPrX_EZLLkq9mSNYLb3oCz1IS7sshvo',
    appId: '1:864142541207:ios:81d6907c90da93523d44d2',
    messagingSenderId: '864142541207',
    projectId: 'complexusdemo-3bc02',
    databaseURL: 'https://complexusdemo-3bc02.firebaseio.com',
    storageBucket: 'complexusdemo-3bc02.appspot.com',
    iosClientId: '864142541207-92173apeqe2dq5gseo38fr6vi7i3p5lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNewsAppp',
  );
}
